spring:
  data:
    mongodb:
      username: toan2002
      password: toan2002
      additional-host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090
